name: skilltest_trimitra
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  get_it: ^8.1.0
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "icons/icon.png"
  remove_alpha_ios: true
